/* 高保真交互原型：数据全部为本地演示；没有后台写入、真实鉴权或网络查询。 */
const paths={search:'M21 21l-5-5 M17 10a7 7 0 1 1-14 0 7 7 0 0 1 14 0',doc:'M14 3H5v18h14V8z M14 3v5h5 M8 12h8 M8 16h6',grid:'M3 3h7v7H3z M14 3h7v7h-7z M3 14h7v7H3z M14 14h7v7h-7z',code:'M8 5L2 12l6 7 M16 5l6 7-6 7 M14 3l-4 18',sign:'M3 20h18 M5 16L16 5l3 3L8 19l-4 1z M15 6l3 3',image:'M3 3h18v18H3z M3 16l6-6 5 5 3-3 4 4 M15 7h.01',chevron:'M9 5l7 7-7 7',down:'M6 9l6 6 6-6',back:'M15 5l-7 7 7 7',close:'M6 6l12 12 M18 6L6 18',download:'M12 3v12 M7 10l5 5 5-5 M4 16v5h16v-5',copy:'M8 8h12v13H8z M16 8V3H3v13h5',expand:'M8 3H3v5 M16 3h5v5 M21 16v5h-5 M8 21H3v-5',collapse:'M3 8h5V3 M16 3v5h5 M21 16h-5v5 M8 21v-5H3',settings:'M4 7h16 M4 17h16 M8 4v6 M16 14v6',refresh:'M20 7v5h-5 M4 17v-5h5 M5 7a8 8 0 0 1 13-2l2 2 M4 17l2 2a8 8 0 0 0 13-2',clock:'M12 7v5l3 2 M22 12a10 10 0 1 1-20 0 10 10 0 0 1 20 0',phone:'M8 3H5c-2 5 3 14 9 17l4 1 3-5-5-2-2 3-7-7 3-2z',hash:'M5 8h15 M4 16h15 M10 3L6 21 M18 3l-4 18',calendar:'M3 6h18v15H3z M7 3v6 M17 3v6 M3 11h18',check:'M5 12l4 4L19 6',shield:'M12 3l8 3v6c0 5-8 9-8 9s-8-4-8-9V6z M8 12l3 3 5-6',more:'M5 12h.01 M12 12h.01 M19 12h.01',list:'M8 6h13 M8 12h13 M8 18h13 M3 6h.01 M3 12h.01 M3 18h.01',panel:'M3 3h18v18H3z M9 3v18',plus:'M12 5v14 M5 12h14',minus:'M5 12h14',lock:'M5 10h14v11H5z M8 10V7a4 4 0 0 1 8 0v3 M12 14v3',wifi:'M3 8a14 14 0 0 1 18 0 M6 12a9 9 0 0 1 12 0 M9 16a4 4 0 0 1 6 0 M12 20h.01',battery:'M2 7h17v10H2z M22 10v4 M5 10h11v4H5z',bell:'M5 16h14l-2-3V8a5 5 0 0 0-10 0v5z M10 20h4',arrow:'M5 12h14 M13 6l6 6-6 6',folder:'M3 6h7l2 3h9v11H3z',key:'M14 7a5 5 0 1 0-10 0 5 5 0 0 0 10 0 M12 11l9 9 M17 16l3-3',info:'M12 11v6 M12 7h.01 M22 12a10 10 0 1 1-20 0 10 10 0 0 1 20 0'};
const icon=(name,cls='')=>`<svg class="icon ${cls}" viewBox="0 0 24 24" aria-hidden="true"><path d="${paths[name]||paths.doc}"/></svg>`;
const esc=v=>String(v??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
const button=(name,title,action,extra='')=>`<button class="icon-btn" aria-label="${title}" title="${title}" data-action="${action}" ${extra}>${icon(name)}</button>`;
const labels={caseNo:'单据号',sysAccept:'受理流水',phoneNo:'手机号码',opMonth:'业务月份',opCode:'业务编码',opName:'业务名称',opTime:'受理时间',sts:'状态编码',stsDesc:'单据状态',loginNo:'受理工号',loginName:'受理人员',groupId:'营业厅编码',groupName:'营业厅名称',areaCode:'区县编码',areaName:'所属区县',regionCode:'地市编码',regionName:'所属地市',provinceCode:'省份编码',provinceName:'所属省份',tenantId:'租户标识',isSign:'是否签字',isPhoto:'是否拍照',isRead:'是否阅读',signNum:'签字数量',photoNum:'图片数量',picSeq:'图片序号',cardNum:'证件图片数',isPreControl:'是否预控',isAgainCreate:'是否重新生成',cdFlag:'处理标记',fileName:'文件路径',ext7:'归档索引',ext8:'加密标识'};
const groupDefs=[['doc','单据与业务',['caseNo','sysAccept','phoneNo','opMonth','opCode','opName','opTime','sts','stsDesc']],['grid','受理与渠道',['loginNo','loginName','groupId','groupName','tenantId']],['folder','归属与地区',['provinceCode','provinceName','regionCode','regionName','areaCode','areaName']],['sign','签署与影像',['isSign','isRead','isPhoto','signNum','photoNum','cardNum','picSeq','isPreControl','isAgainCreate','cdFlag']],['code','归档与扩展',['fileName',...Array.from({length:10},(_,i)=>`ext${i+1}`)]]];
function demoWork(i=0,month='202609',phone='13800000000'){
 const names=['移动业务受理单','宽带业务受理单','套餐变更受理单'];
 const w={caseNo:`${month}120925000000${String(186+i).padStart(4,'0')}`,sysAccept:`JS${month}1200000${String(928+i).padStart(4,'0')}`,phoneNo:phone,opMonth:month,opCode:['BP003','BP018','BP021'][i%3],opName:names[i%3],opTime:`${month.slice(0,4)}-${month.slice(4)}-12 ${['14:32:06','11:08:42','09:16:28'][i%3]}`,sts:'1',stsDesc:'已归档',loginNo:'DEMO02501',loginName:'演示受理员',groupId:'NJ_DEMO_001',groupName:'南京 · 演示营业厅',areaCode:'02501',areaName:'鼓楼区',regionCode:'025',regionName:'南京',provinceCode:'32',provinceName:'江苏',tenantId:'DEMO',isSign:'1',isPhoto:'1',isRead:'1',isPreControl:'0',isAgainCreate:'0',signNum:'2',cardNum:'2',photoNum:'3',picSeq:'1,2,3',cdFlag:'0',fileName:`/receipt025/${month}/demo/${186+i}.pdf`};
 for(let n=1;n<=10;n++)w[`ext${n}`]=n===7?`${month}/receipt025`:n===8?'0':null;
 return w;
}
let mobile=location.search.includes('surface=phone')||innerWidth<600;
const state={works:[demoWork(0),demoWork(1),demoWork(2)],selected:mobile?null:0,view:'details',grouped:true,fieldQuery:'',orderQuery:'',fit:'page',thumbs:!mobile,zoom:100,pdfPage:1,pdfFull:false,query:{kind:'phoneNo',value:'13800000000',start:'2026-09',end:'2026-09',range:false},queryLabel:'手机号码 · 13800000000',queriedAt:'刚刚',cache:new Map(),cacheHits:0,logs:[],settings:{baseUrl:'https://demo.example.invalid/npl',bucket:''},modal:null,scenario:'normal',running:null,messageIndex:0,messageMode:'auto',messageRaw:false,messageCollapsed:new Set(),messageKey:'',messageKeyword:'',frames:[],historyCleared:false,history:[],table:'WO_INFO',tableResult:null,previousFocus:null};
const work=()=>state.works[state.selected??0]||demoWork();
const navs=[['details','doc','单据信息',''],['pdf','doc','单据 PDF','3'],['message','code','报文信息','3'],['sign','sign','签字信息','2'],['picture','image','图片信息','3']];
const app=document.querySelector('#app'),overlay=document.querySelector('#overlay');
let toastTimer;
function toast(text){const t=document.querySelector('#toast');t.textContent=text;t.classList.add('visible');clearTimeout(toastTimer);toastTimer=setTimeout(()=>t.classList.remove('visible'),2400)}
function refreshMobile(){const next=location.search.includes('surface=phone')||innerWidth<600;if(next!==mobile){mobile=next;render()}}
window.addEventListener('resize',()=>{refreshMobile();applyZoom()});
function orderCard(w,i){return `<button class="order-card ${state.selected===i?'selected':''}" data-action="choose" data-id="${i}"><div class="row"><h4 class="grow">${esc(w.opName)}</h4>${mobile?icon('chevron','card-arrow'):''}</div><span class="mono">${esc(w.caseNo)}</span>${mobile?`<span class="mono">${esc(w.phoneNo)}　·　${esc(w.groupName)}</span>`:''}<footer><span>${esc(w.opTime.slice(5,16))}</span><span class="badge green"><i></i>已归档</span></footer></button>`}
function desktopSidebar(){return `<aside class="sidebar"><div class="sidebar-head"><h3>查询结果 <span style="margin-left:6px">${state.works.length}</span></h3>${button('refresh','刷新查询结果','requery')}</div><div class="result-filter">${icon('search')}<input aria-label="筛选工单" placeholder="在结果中筛选" id="order-filter" value="${esc(state.orderQuery)}"></div><div class="orders">${state.works.map((w,i)=>JSON.stringify(w).toLowerCase().includes(state.orderQuery.toLowerCase())?orderCard(w,i):'').join('')||'<div class="muted" style="padding:20px;font-size:11px">未找到匹配工单</div>'}</div><div class="sidebar-bottom">${icon('clock')} 查询完成 · ${state.queriedAt}</div></aside>`}
function mobileHeader(){return `<div class="mobile-header"><div class="statusbar"><span>9:41</span><div class="island"></div><span class="signals">▮▮▮ ${icon('wifi')}${icon('battery')}</span></div><div class="mobile-brand">${state.selected===null?`<h1>无纸化维护中心</h1>`:`<button class="back-label" data-action="results">${icon('back')}工单列表</button><strong>${navs.find(n=>n[0]===state.view)?.[2]||'单据详情'}</strong>`}<div class="row">${state.selected!==null?button('search','搜索工单','search'):''}${button('more','更多操作','more')}</div></div>${state.selected===null?`<button class="search-launch" data-action="search">${icon('search')}<span>${esc(state.queryLabel)}</span><span class="filter-trigger">${icon('settings')}</span></button>`:''}</div>`}
function mobileBottom(){return `<nav class="mobile-bottom" aria-label="资料分类">${navs.map(([key,ic,label])=>`<button data-action="nav" data-id="${key}" class="${state.view===key?'active':''}">${icon(ic)}<span>${({details:'单据',pdf:'PDF',message:'报文',sign:'签字',picture:'图片'})[key]}</span></button>`).join('')}</nav>`}
function render(){
 document.body.classList.toggle('mobile',mobile);
 app.innerHTML=`<div class="app-shell"><header class="topbar"><div class="brandmark"><img src="app-icon.png" alt=""><div><b>无纸化维护中心</b><small>WORK ORDER CENTER</small></div></div><button class="global-search" data-action="search">${icon('search')}<strong>${esc(state.queryLabel)}</strong><span class="divider"></span><span>${esc(state.query.start)}${state.query.range?' — '+esc(state.query.end):''}</span><kbd>⌘ K</kbd></button><span class="top-status"><i class="dot"></i>只读 · 缓存命中 ${state.cacheHits} 次</span><div class="top-actions"><span class="online"><i></i>演示环境</span><button class="text-btn" data-action="data-query">数据查询</button><button class="text-btn" data-action="logs">接口记录${state.logs.length?' · '+state.logs.length:''}</button><button class="text-btn" data-action="settings">设置</button><span class="divider"></span><div class="avatar">只读</div></div></header>${mobileHeader()}${desktopSidebar()}<main class="workspace">${state.selected!==null?desktopHead():''}<div class="content" id="content">${content()}</div></main>${mobileBottom()}</div>`;
 bindPdfScroll();
}
function desktopHead(){const w=work();return `<section class="work-head"><div class="work-title"><div class="row grow" style="min-width:0"><h1>${esc(w.opName)}</h1><span class="badge green"><i></i>已归档</span><span class="title-meta"><span class="mono">${esc(w.caseNo)}</span><span class="divider"></span>${esc(w.regionName)} · ${esc(w.groupName.split(' · ')[1])}<span class="divider"></span>${esc(w.opTime)}</span></div><div class="row"><button class="btn quiet" data-action="copy-work">${icon('copy')}复制单据号</button><button class="btn" data-action="export-work">${icon('download')}导出信息</button></div></div><nav class="tabs">${navs.map(([k,ic,l,n])=>`<button class="tab ${state.view===k?'active':''}" data-action="nav" data-id="${k}">${icon(ic)}${l}${n?`<em>${n}</em>`:''}</button>`).join('')}<div class="tab-end">${icon('shield')}只读查询</div></nav></section>`}
function content(){
 if(state.selected===null)return mobile?mobileResults():`<div class="empty-state">${icon('doc')}<h3>${state.works.length?'选择一份工单，开始核对':'没有找到相关工单'}</h3><p>${state.works.length?'从左侧选择工单，单据详情与 PDF 将在这里并排展示。':'调整查询条件或月份，再试一次。'}</p><button class="btn primary" data-action="search">${icon('search')}重新查询</button></div>`;
 if(state.view==='details')return `<div class="details-only">${mobile?mobileWorkSummary():''}${detailsPanel()}</div>`;
 if(state.view==='pdf')return `<div class="pdf-view ${state.pdfFull?'reading-fullscreen':''}">${pdfPanel()}</div>`;
 if(state.view==='message')return messageView();
 return galleryView(state.view);
}
function mobileResults(){return `<section class="mobile-results"><div class="result-summary"><b>${state.works.length} 份相关单据</b><span>${state.queriedAt}更新</span></div><div class="row" style="margin-bottom:16px;gap:6px;flex-wrap:wrap"><span class="search-token">${icon('calendar')}${state.query.start}${state.query.range?' 至 '+state.query.end:''}</span><span class="search-token">${state.works.length} 份工单</span><button class="muted" style="margin-left:auto;font-size:10px" data-action="search">修改条件</button></div>${state.works.map(orderCard).join('')||`<div class="empty-state">${icon('search')}<h3>没有找到相关单据</h3><p>换一个单据号，或扩大月份范围。</p><button class="btn primary" data-action="search">修改查询条件</button></div>`}<div class="result-info">${icon('check')}选择单据后，查看完整关联资料</div></section>`}
function mobileWorkSummary(){const w=work();return `<section class="mobile-work-summary"><div class="badges"><span class="badge green"><i></i>已归档</span><span class="badge">${esc(w.regionName)} · ${esc(w.opMonth.slice(0,4))}-${esc(w.opMonth.slice(4))}</span></div><h2>${esc(w.opName)}</h2><div class="summary-meta"><span class="mono">${esc(w.caseNo)}</span>${button('copy','复制单据号','copy-work')}<button class="icon-btn" aria-label="导出单据信息" data-action="export-work">${icon('download')}</button></div></section>`}
function detailsPanel(){return `<section class="details-panel"><div class="detail-tools"><div class="segmented"><button data-action="field-mode" data-id="group" class="${state.grouped?'active':''}">业务分组</button><button data-action="field-mode" data-id="all" class="${!state.grouped?'active':''}">全部字段</button></div><div class="field-search">${icon('search')}<input id="field-search" aria-label="搜索单据字段" placeholder="搜索字段或内容" value="${esc(state.fieldQuery)}"></div></div><div class="details-scroll" id="fields-content">${fieldsMarkup()}</div><footer class="info-foot"><span>完整返回 · ${Object.keys(work()).length} 个字段 · 含空值</span><button data-action="export-work" style="font-size:9px;color:#698bb5">导出 JSON ↗</button></footer></section>`}
function highlight(v,q){const text=String(v??'');if(!q)return esc(text);const at=text.toLowerCase().indexOf(q.toLowerCase());return at<0?esc(text):esc(text.slice(0,at))+'<mark>'+esc(text.slice(at,at+q.length))+'</mark>'+esc(text.slice(at+q.length))}
function fieldsMarkup(){const w=work(),q=state.fieldQuery.trim().toLowerCase(),groups=state.grouped?groupDefs:[['list','全部接口字段',Object.keys(w)]];let matched=0;
 const sections=groups.map(([ic,title,keys])=>{const entries=keys.filter(k=>k in w&&(!q||`${labels[k]||''} ${k} ${w[k]??'空值'}`.toLowerCase().includes(q)));matched+=entries.length;if(!entries.length)return'';return `<details class="field-group" open><summary><i class="group-bar"></i>${title}<small>${entries.length} 项</small>${icon('down','chev')}</summary><div class="field-grid">${entries.map(k=>`<div class="field ${['caseNo','sysAccept','groupName','fileName'].includes(k)?'wide':''}"><label>${highlight(labels[k]||'扩展字段 '+k.slice(3),q)}<code>${highlight(k,q)}</code></label><div class="value ${w[k]===null?'empty':''} ${['caseNo','sysAccept','fileName'].includes(k)?'mono':''}">${w[k]===null?'— <small style="font-size:9px">未返回值</small>':highlight(w[k],q)}</div>${button('copy','复制 '+(labels[k]||k),'copy-field',`data-id="${k}"`).replace('icon-btn','icon-btn copy-field')}</div>`).join('')}</div></details>`}).join('');
 return `${!q?`<div class="summary-strip"><div><small>业务月份</small><strong class="mono">${w.opMonth.slice(0,4)}-${w.opMonth.slice(4)}</strong></div><div><small>签署情况</small><strong class="green-text">${icon('check')} 已签署</strong></div><div><small>关联文件</small><strong>9 <small style="display:inline">份</small></strong></div></div>`:`<p class="message-hint" style="padding-top:15px">找到 ${matched} 个匹配字段 · 保留完整内容</p>`}${sections||'<div class="empty-state"><p>没有匹配字段，请换一个关键词。</p></div>'}`;
}
function paper(n){const w=work();return `<article class="paper" id="pdf-page-${n}" data-page="${n}"><header class="paper-label"><span class="paper-logo">无纸化 · 电子单据</span><span>江苏 / ${esc(w.regionName)}</span></header><div class="watermark">演 示 单 据</div><h2>${n===1?w.opName:n===2?'业务办理事项告知':'客户签署确认页'}</h2><div class="serial">单据编号：${esc(w.caseNo)} · 演示文件</div>${n===1?`<table><tr><td>客户号码</td><td>${esc(w.phoneNo)}</td><td>业务月份</td><td>${w.opMonth}</td></tr><tr><td>受理流水</td><td colspan="3">${esc(w.sysAccept)}</td></tr><tr><td>办理业务</td><td colspan="3">${esc(w.opName)}</td></tr><tr><td>受理网点</td><td colspan="3">${esc(w.groupName)}</td></tr></table><h3>一、业务受理内容</h3><p>客户申请办理相关通信业务。业务内容、受理时间及办理渠道以本单据所载信息为准。本电子单据与对应业务记录关联，可用于信息核对与归档查阅。</p><h3>二、业务信息确认</h3><p>本人已阅读并确认本次业务受理内容，知悉相关业务说明及服务约定。经核对，上述业务信息与本次申请一致。</p><div class="sign-line"><span>客户签字：<span class="demo-sign">演示签字</span></span><span>${esc(w.opTime.slice(0,10))}</span></div>`:n===2?`<h3>一、业务内容说明</h3><p>请在办理前仔细阅读业务说明，了解业务适用条件、办理方式和生效时间。如对业务内容有疑问，可向受理人员咨询并确认。</p><h3>二、服务与权益说明</h3><p>业务办理后，客户可通过服务渠道查询业务状态及有关记录。有关服务内容以双方确认的业务受理信息和相关约定为准。</p><h3>三、信息使用与保存</h3><p>与本次业务有关的电子单据、签字和受理信息应妥善保存。客户可根据需要查询业务办理记录。</p><h3>四、其他事项</h3><p>本页为高保真界面中的演示文档，仅用于验证连续阅读、缩放、缩略图导航和文档核对体验，不具有业务或法律效力。</p><p class="paper-note">以上内容均为本地演示数据。</p>`:`<h3>客户确认</h3><p>本人确认已阅读前述业务受理信息和业务办理事项告知，并确认各项内容。以下为模拟签署区域，仅用于本地界面展示。</p><table><tr><td>单据号</td><td>${esc(w.caseNo)}</td></tr><tr><td>受理工号</td><td>${esc(w.loginNo)}</td></tr><tr><td>签署状态</td><td>已完成</td></tr></table><div class="sign-line" style="margin-top:22%"><span>客户签字</span><span class="demo-sign">演示签字</span></div><div class="sign-line" style="margin-top:4%"><span>受理人员：${esc(w.loginName)}</span><span>${esc(w.opTime.slice(0,10))}</span></div>`}${n!==2?`<span class="seal">演示受理<b>专用章</b></span>`:''}<footer class="paper-foot"><span>本地演示 · 非真实业务凭证</span><span>${n} / 3</span></footer></article>`}
function pdfPanel(){const w=work(),head=mobile?`<header class="pdf-head"><div class="filetype">PDF</div><div class="grow"><span class="file-title">${esc(w.opName)}.pdf</span><small>3 页 · 286 KB · 已读取</small></div>${button('download','下载 PDF','download-pdf')}${button(state.pdfFull?'collapse':'expand',state.pdfFull?'退出全屏':'全屏阅读','pdf-full')}</header><div class="pdf-toolbar"><div class="row">${button('panel','显示或隐藏缩略图','thumbnails')}<span class="divider"></span><span><b id="current-page">${state.pdfPage}</b> / 3</span></div><div class="row">${button('minus','缩小','zoom-out')}<span id="zoom-label">${state.zoom}%</span>${button('plus','放大','zoom-in')}<span class="divider"></span><select id="pdf-fit" aria-label="PDF 适应方式">${[['width','适应宽度'],['page','适应整页'],['actual','实际大小']].map(([v,l])=>`<option value="${v}" ${state.fit===v?'selected':''}>${l}</option>`).join('')}</select></div></div>`:`<header class="pdf-head merged"><div class="filetype">PDF</div><div class="grow"><span class="file-title">${esc(w.opName)}.pdf</span><small>3 页 · 286 KB</small></div>${button('panel','显示或隐藏缩略图','thumbnails')}<span class="divider"></span><span class="page-ind"><b id="current-page">${state.pdfPage}</b> / 3</span>${button('minus','缩小','zoom-out')}<span id="zoom-label">${state.zoom}%</span>${button('plus','放大','zoom-in')}<select id="pdf-fit" aria-label="PDF 适应方式">${[['width','适应宽度'],['page','适应整页'],['actual','实际大小']].map(([v,l])=>`<option value="${v}" ${state.fit===v?'selected':''}>${l}</option>`).join('')}</select><span class="divider"></span>${button('download','下载 PDF','download-pdf')}${button(state.pdfFull?'collapse':'expand',state.pdfFull?'退出全屏':'全屏阅读','pdf-full')}</header>`;return `<section class="document-panel">${head}<div class="pdf-body">${state.thumbs?`<aside class="thumbs ${mobile?'show-mobile':''}" aria-label="PDF 缩略图">${[1,2,3].map(n=>`<button class="thumb ${n===state.pdfPage?'active':''}" data-action="pdf-page" data-id="${n}"><div class="mini-paper"><i></i><i></i><i></i><div class="minibox"></div><i></i><i></i></div><span>${n}</span></button>`).join('')}</aside>`:''}<div class="pdf-pages" id="pdf-pages">${[1,2,3].map(paper).join('')}</div></div><footer class="pdf-status"><span class="row">${icon('check')}连续阅读 · 滚动浏览全部页面</span><span>${mobile?'双指缩放':'双指或按钮缩放'}</span></footer></section>`}
// PDF 演示页为可缩放的纸张排版，不用截屏冒充可编辑的控件。
function bindPdfScroll(){const pages=document.querySelector('#pdf-pages');if(!pages)return;applyZoom();pages.addEventListener('scroll',()=>{const top=pages.getBoundingClientRect().top;let current=1;pages.querySelectorAll('.paper').forEach(p=>{if(p.getBoundingClientRect().top-top<pages.clientHeight*.45)current=+p.dataset.page});state.pdfPage=current;document.querySelector('#current-page').textContent=current;document.querySelectorAll('.thumb').forEach(t=>t.classList.toggle('active',+t.dataset.id===current))},{passive:true});let touchDistance=0,startZoom=100;pages.addEventListener('touchstart',e=>{if(e.touches.length===2){touchDistance=Math.hypot(e.touches[0].clientX-e.touches[1].clientX,e.touches[0].clientY-e.touches[1].clientY);startZoom=state.zoom}},{passive:true});pages.addEventListener('touchmove',e=>{if(e.touches.length===2&&touchDistance){e.preventDefault();const d=Math.hypot(e.touches[0].clientX-e.touches[1].clientX,e.touches[0].clientY-e.touches[1].clientY);state.zoom=Math.max(65,Math.min(190,Math.round(startZoom*d/touchDistance)));applyZoom()}},{passive:false})}
// 纸张基准宽度由 CSS 变量 --paper-base 决定，宽屏断点会放大它。
// fit=page（默认）时按可视区高度反推缩放，保证一整页完整入屏、无需滚动。
function applyZoom(){const base=parseFloat(getComputedStyle(document.documentElement).getPropertyValue('--paper-base'))||680;const pages=document.querySelector('#pdf-pages');let zoom=state.zoom;
 if(state.fit==='page'&&pages){const cs=getComputedStyle(pages),availW=pages.clientWidth-parseFloat(cs.paddingLeft)-parseFloat(cs.paddingRight),availH=pages.clientHeight-parseFloat(cs.paddingTop)-parseFloat(cs.paddingBottom)-24;zoom=Math.max(40,Math.min(190,Math.floor(Math.min(availW/base,availH*210/(297*base))*100)))}
 document.querySelectorAll('.paper').forEach(p=>{p.style.width=zoom+'%';p.style.maxWidth=base*zoom/100+'px';p.style.minWidth=0;p.style.setProperty('--pz',zoom/100)});const z=document.querySelector('#zoom-label');if(z)z.textContent=zoom+'%'}
const signSvg=`<svg viewBox="0 0 400 150" aria-label="演示笔迹"><path d="M45 60q-10-35 16-30t0 90m-23-46l66-14m-38-18l36 48m-67 34q50-15 82-25M138 37l-20 90m7-65q67-42 44-16t-24 66q18 14 56-30M226 30l-18 95m-1-49l68-25m-37-12q58 72 25 70l-39-14M299 55q-13-34 10-17t-3 59q25-46 48-39t-20 58m-36 12l66-15"/></svg>`;
function galleryView(type){const count=type==='sign'?2:3;return `<section class="gallery-view"><div class="panel-header"><div><h3>${type==='sign'?'签字影像':'关联图片'}</h3><small>共 ${count} 份 · 全部连续展示</small></div><button class="btn" data-action="download-gallery">${icon('download')}下载全部</button></div><div class="gallery" style="grid-template-columns:repeat(${count},minmax(0,1fr))">${Array.from({length:count},(_,i)=>`<article class="image-card"><header><h4>${type==='sign'?['客户签字','受理人员签字'][i]:['证件正面 · 演示','证件反面 · 演示','业务附件 · 演示'][i]}</h4><div class="row">${button('download','下载此图片','download-image',`data-id="${i}"`)}${button('expand','全屏查看','image-full',`data-id="${i}"`)}</div></header><div class="sample-image">${type==='sign'?signSvg:`<div class="placeholder-card"><h3>演示资料 · ${i+1}</h3><i class="line-shape"></i><i class="line-shape"></i><i class="line-shape"></i><div class="avatar-shape"></div></div>`}</div><footer><span>${type==='sign'?'signature':'attachment'}_${String(i+1).padStart(2,'0')}.svg</span><span>演示矢量图片</span></footer></article>`).join('')}</div></section>`}
// 递归解析和专注保留原始值，可沿面包屑跨 JSON / XML 反复深入。
function messageSamples(){return [JSON.stringify({caseNo:work().caseNo,cmdCode:'BP003',requestTime:work().opTime,business:{phoneNo:work().phoneNo,opMonth:work().opMonth,regionCode:'025'},crmResponse:'<response><resultCode>0000</resultCode><payload><![CDATA[{"status":"SUCCESS","data":{"receiptId":"DEMO-0186","signed":true}}]]></payload></response>'},null,2),`<acceptance caseNo="${work().caseNo}"><channel>营业厅</channel><phoneNo>${work().phoneNo}</phoneNo><detail><![CDATA[{"business":"移动业务受理","attachments":[{"name":"receipt.pdf","pages":3},{"name":"signature.svg","count":2}]}]]></detail></acceptance>`,JSON.stringify({caseNo:work().caseNo,h5:{state:'completed',signatures:[{name:'客户签字',signed:true},{name:'受理人员签字',signed:true}]},extra:'{"archive":{"bucket":"receipt025","ext8":"0"}}'},null,2)]}
function xmlValue(el){const children=[...el.children];if(!children.length&&!el.attributes.length)return el.textContent;const result={};for(const a of el.attributes)result['@'+a.name]=a.value;for(const child of children){const v=xmlValue(child);if(child.tagName in result){if(!Array.isArray(result[child.tagName]))result[child.tagName]=[result[child.tagName]];result[child.tagName].push(v)}else result[child.tagName]=v}if(!children.length&&el.textContent.trim())result['#text']=el.textContent;return result}
function parseMessage(raw,mode='auto'){if(typeof raw!=='string')return{format:'JSON',value:raw,source:JSON.stringify(raw,null,2)};if(mode==='text')return{format:'文本',value:raw,source:raw};if(mode!=='xml'){try{let v=JSON.parse(raw);if(typeof v==='string'&&mode==='auto'&&/^[\[{<]/.test(v.trim()))return parseMessage(v);return{format:'JSON',value:v,source:raw}}catch{if(mode==='json')return{format:'文本',value:raw,source:raw,error:'JSON 解析失败，已保留完整原文。'}}}if(mode!=='json'){const xml=new DOMParser().parseFromString(raw,'application/xml');if(!xml.querySelector('parsererror'))return{format:'XML',value:{[xml.documentElement.tagName]:xmlValue(xml.documentElement)},source:raw};if(mode==='xml')return{format:'文本',value:raw,source:raw,error:'XML 解析失败，已保留完整原文。'}}return{format:'文本',value:raw,source:raw}}
function currentMessage(){if(!state.frames.length)state.frames=[{label:'原始报文',value:messageSamples()[state.messageIndex]}];return parseMessage(state.frames.at(-1).value,state.messageMode)}
function messageView(){const parsed=currentMessage();return `<section class="message-view"><div class="panel-header"><div><h3>报文阅读器</h3><small>字段支持继续解析与专注</small></div><div class="row">${button('copy','复制当前报文','copy-message')}${button('download','下载当前报文','download-message')}${button('expand','全屏报文','message-full')}</div></div><div class="message-tools"><select class="input-small" id="message-file" aria-label="选择报文文件">${[work().caseNo+'_'+work().opCode+'.txt',work().caseNo+'_'+work().opCode+'_oprInfo.txt',work().caseNo+'_'+work().opCode+'_h5.txt'].map((n,i)=>`<option value="${i}" ${state.messageIndex===i?'selected':''}>${n}</option>`).join('')}</select><select class="input-small" id="message-format" aria-label="报文解析方式">${[['auto','自动识别'],['json','JSON'],['xml','XML'],['text','纯文本']].map(([v,l])=>`<option value="${v}" ${state.messageMode===v?'selected':''}>${l}</option>`).join('')}</select><button class="btn quiet" data-action="message-raw">${state.messageRaw?'结构视图':'原文'}</button><button class="btn quiet" data-action="message-fold">折叠 / 展开</button><input class="input-small" id="message-key" placeholder="字段名 / key" aria-label="搜索报文字段名" value="${esc(state.messageKey)}"><input class="input-small" id="message-keyword" placeholder="内容关键字" aria-label="搜索报文内容" value="${esc(state.messageKeyword)}"></div><div class="message-path">${icon('code')}${state.frames.map((f,i)=>`<button data-action="message-back" data-id="${i}">${esc(f.label)}</button>${i<state.frames.length-1?icon('chevron'):''}`).join('')}<span class="badge blue" style="margin-left:auto">${parsed.format}</span></div><div class="message-tree" id="message-tree">${messageTree()}</div></section>`}
let visibleNodes=[];
function messageTree(){const p=currentMessage();visibleNodes=[];if(state.messageRaw||p.format==='文本')return `${p.error?`<p class="form-error">${esc(p.error)}</p>`:''}<p class="message-hint">完整原文 · 不分页</p><pre class="raw-text">${highlight(p.source,state.messageKeyword)}</pre>`;
 const qk=state.messageKey.toLowerCase(),qv=state.messageKeyword.toLowerCase(),searching=qk||qv,rows=[];
 function visit(name,value,path,depth){const branch=value!==null&&typeof value==='object',summary=branch?`${Array.isArray(value)?'数组':'对象'} · ${Object.keys(value).length} 个字段`:String(value),matches=(!qk||name.toLowerCase().includes(qk))&&(!qv||(!branch&&summary.toLowerCase().includes(qv)));if(!searching||matches){const id=visibleNodes.push({name,value,path})-1;rows.push(`<div class="tree-row" style="padding-left:${searching?0:Math.min(depth,mobile?3:10)*13}px"><button class="tree-toggle" data-action="tree-toggle" data-id="${esc(path)}" aria-label="${state.messageCollapsed.has(path)?'展开':'折叠'} ${esc(name)}">${branch?(state.messageCollapsed.has(path)?'▸':'▾'):'·'}</button><span class="tree-key">${highlight(name,state.messageKey)}</span><span class="tree-value">${highlight(summary.length>160?summary.slice(0,160)+'…':summary,state.messageKeyword)}</span><button class="tree-focus" data-action="message-focus" data-id="${id}">专注</button></div>`)}if(branch&&(searching||!state.messageCollapsed.has(path)))Object.entries(value).forEach(([k,v])=>visit(k,v,path+'/'+k,depth+1))}
 visit('$',p.value,'$',0);return `<p class="message-hint">${searching?'找到 '+rows.length+' 个字段':'点击箭头折叠 · 点击“专注”继续解析字段内的 JSON / XML'}</p>${rows.join('')||'<p class="muted">没有匹配字段。</p>'}`;
}
function refreshMessage(){const parent=document.querySelector('.message-view')?.parentElement;if(parent){parent.innerHTML=messageView()}}
// 对话框管理同时负责键盘焦点和返回操作。
function showDialog(title,body,foot='',cls=''){state.previousFocus=document.activeElement;overlay.innerHTML=`<div class="scrim"><section class="dialog ${cls}" role="dialog" aria-modal="true" aria-label="${esc(title)}" tabindex="-1"><header class="dialog-head"><div><h2>${title}</h2><p>${cls==='search-dialog'?'找到这一次受理的全部信息':'无纸化维护中心 · 本地交互预览'}</p></div>${button('close','关闭面板','close')}</header><div class="dialog-body">${body}</div>${foot?`<footer class="dialog-foot">${foot}</footer>`:''}</section></div>`;overlay.querySelector('.dialog').focus()}
function closeDialog(){if(state.running)return toast('查询正在进行，可先取消查询。');overlay.innerHTML='';state.modal=null;state.previousFocus?.focus?.()}
function searchBody(){const q=state.query;return `<div class="search-kinds">${[['phoneNo','phone','手机号码'],['sysAccept','hash','受理流水'],['caseNo','doc','单据号']].map(([k,ic,l])=>`<button class="search-kind ${q.kind===k?'active':''}" data-action="query-kind" data-id="${k}">${icon(ic)}${l}</button>`).join('')}</div><label class="form-label" for="query-value">${labels[q.kind]}<small>${q.kind==='phoneNo'?'11 位手机号码':'请输入完整号码'}</small></label><input class="big-input" id="query-value" inputmode="${q.kind==='phoneNo'?'tel':'text'}" autocomplete="off" placeholder="${q.kind==='phoneNo'?'例如 13800000000':q.kind==='sysAccept'?'输入受理流水号':'输入完整单据号'}" value="${esc(q.value)}"><p class="field-help">${q.kind==='caseNo'?'系统会根据单据号定位工单，无需额外选择月份。':'按号码与月份组合查询，支持跨月查找关联工单。'}</p>${q.kind!=='caseNo'?`<div class="month-title"><span>业务月份</span><div class="segmented"><button class="${!q.range?'active':''}" data-action="query-range" data-id="single">单月</button><button class="${q.range?'active':''}" data-action="query-range" data-id="range">范围</button></div></div><div class="month-inputs"><label>${q.range?'起始月份':'选择月份'}<input type="month" id="query-start" aria-label="起始月份" value="${q.start}"></label>${q.range?`<span style="padding-top:17px;color:#a2adbb">—</span><label>结束月份<input type="month" id="query-end" aria-label="结束月份" value="${q.end}"></label>`:''}</div><div class="month-shortcuts"><button data-action="query-shortcut" data-id="1">本月</button><button data-action="query-shortcut" data-id="3">最近 3 个月</button><button data-action="query-shortcut" data-id="6">最近 6 个月</button></div><p class="field-help" style="margin-bottom:0">${q.range?'按月份逐次查询，可随时取消 · 首尾合计最多 12 个月':'仅查询选中月份，避免加载无关数据'}</p>`:''}<div id="query-error"></div><div class="search-recent"><h4 class="row between"><span>最近查询</span><button data-action="clear-history" style="font-size:10px;color:#a2b0c1">清空</button></h4>${(state.history.length||state.historyCleared?state.history:[{kind:'phoneNo',value:'13800000000',start:'2026-09',end:'2026-09',range:false},{kind:'sysAccept',value:'JS20260912000000928',start:'2026-09',end:'2026-09',range:false}]).slice(0,3).map((h,i)=>`<button class="recent-item" data-action="history" data-id="${i}">${icon('clock')}<span>${esc(h.value)}</span><small>${h.start}${h.range?' — '+h.end:''}</small></button>`).join('')}</div><div class="demo-note">演示场景：<button data-action="scenario" data-id="normal" style="color:${state.scenario==='normal'?'#2869e8':'#92a0b3'}">正常结果</button> · <button data-action="scenario" data-id="empty" style="color:${state.scenario==='empty'?'#2869e8':'#92a0b3'}">无结果</button> · <button data-action="scenario" data-id="error" style="color:${state.scenario==='error'?'#2869e8':'#92a0b3'}">查询失败</button></div>`}
function openSearch(){state.modal='search';showDialog('查询工单',searchBody(),`<span class="privacy-note">${icon('shield')}只读查询 · 演示数据</span><button class="btn primary" data-action="run-search">${icon('search')}查询工单</button>`,'search-dialog')}
function getMonths(){const q=state.query;if(!q.value.trim())throw Error('请先填写'+labels[q.kind]);if(q.kind==='phoneNo'&&!/^1[3-9]\d{9}$/.test(q.value.trim()))throw Error('请输入完整的 11 位手机号码');if(q.kind==='caseNo')return[q.start.replace('-','')];const parse=m=>{if(!/^\d{4}-(0[1-9]|1[0-2])$/.test(m))throw Error('请选择有效的业务月份');return +m.slice(0,4)*12+(+m.slice(5)-1)};const a=parse(q.start),b=q.range?parse(q.end):a;if(b<a)throw Error('结束月份不能早于起始月份');if(b-a>=12)throw Error('月份范围最多 12 个月（包含起止月份）');return Array.from({length:b-a+1},(_,i)=>`${Math.floor((a+i)/12)}${String((a+i)%12+1).padStart(2,'0')}`)}
function progressBody(months,done){return `<div class="query-running">${icon('search')}<h3>正在查找关联工单</h3><p>按月依次查询，已完成的结果会为你保留</p></div><div class="progress-status"><span>${done===months.length?'正在整理结果…':'正在查询 '+months[done].slice(0,4)+' 年 '+months[done].slice(4)+' 月'}</span><b>${done} / ${months.length}</b></div><div class="progress-track"><i style="width:${done/months.length*100}%"></i></div><div class="month-chips">${months.map((m,i)=>`<span class="month-chip ${i<done?'done':i===done?'running':''}">${i<done?'✓ ':''}${m.slice(0,4)}.${m.slice(4)}</span>`).join('')}</div><p class="field-help">切换前请等待完成，或取消并查看已查询的结果。</p>`}
function runSearch(force=false){let months;try{months=getMonths()}catch(e){document.querySelector('#query-error').innerHTML=`<p class="form-error">${esc(e.message)}</p>`;return}const cacheKey=JSON.stringify([state.query,state.settings,state.scenario]);if(!force&&state.cache.has(cacheKey)){state.cacheHits++;finishSearch(state.cache.get(cacheKey),false,true);return}let done=0,rows=[];state.running={cancelled:false};showDialog('查询进行中',progressBody(months,0),`<button class="btn cancel-search" data-action="cancel-query">取消查询</button><span class="privacy-note">已完成月份的结果仍可查看</span>`,'search-dialog');const active=state.running;function step(){if(active.cancelled)return;const q=state.query,m=months[done],body=q.kind==='caseNo'?{caseNo:q.value}:{[q.kind]:q.value,opMonth:m};if(state.scenario==='error'){state.logs.unshift({path:'/api/wo/queryList',body,status:503,response:{message:'演示：服务暂时不可用'}});state.running=null;showDialog('查询暂未完成',`<div class="empty-state" style="height:230px">${icon('info')}<h3>服务暂时不可用</h3><p>本次为失败场景演示。可以重试，或在接口记录中查看请求详情。</p></div>`,`<button class="btn" data-action="logs">查看接口记录</button><button class="btn primary" data-action="retry-query">重试查询</button>`);return}const batch=state.scenario==='empty'?[]:Array.from({length:months.length===1?3:1},(_,i)=>demoWork(i,m,q.kind==='phoneNo'?q.value:'13800000000'));rows.push(...batch);state.logs.unshift({path:'/api/wo/queryList',body,status:200,response:batch});done++;active.rows=rows;overlay.querySelector('.dialog-body').innerHTML=progressBody(months,done);if(done<months.length)active.timer=setTimeout(step,330);else active.timer=setTimeout(()=>{state.running=null;state.cache.set(cacheKey,rows);finishSearch(rows,false,false)},350)}active.timer=setTimeout(step,400)}
function finishSearch(rows,cancelled=false,cached=false){state.running=null;state.works=rows;state.selected=null;state.view='details';state.queryLabel=`${labels[state.query.kind]} · ${state.query.value}`;state.queriedAt=cached?'缓存命中':'刚刚';state.orderQuery='';state.history=[{...state.query},...state.history.filter(h=>JSON.stringify(h)!==JSON.stringify(state.query))].slice(0,5);overlay.innerHTML='';state.modal=null;render();toast(cancelled?`已取消 · 保留 ${rows.length} 份工单`:cached?`已从缓存读取 ${rows.length} 份工单`:`查询完成 · ${rows.length} 份工单`)}
function logsDialog(){state.modal='logs';showDialog('接口查询记录',`<div class="row between" style="margin-bottom:15px"><span class="badge blue">演示请求 · ${state.logs.length} 次</span><button class="btn quiet" data-action="cache-clear">${icon('refresh')}清空缓存 (${state.cacheHits})</button></div>${state.logs.length?state.logs.map((l,i)=>`<details class="log-entry" ${i===0?'open':''}><summary>${icon('code')}POST ${esc(l.path)}<span class="badge ${l.status===200?'green':'orange'}">${l.status}</span></summary><pre>${esc(`URL: ${state.settings.baseUrl}${l.path}\nMethod: POST\n\n请求\n${JSON.stringify(l.body,null,2)}\n\n响应\n${JSON.stringify(l.response,null,2)}`)}</pre></details>`).join(''):'<div class="empty-state" style="height:250px"><p>还没有查询记录，先试试查询工单。</p></div>'}<p class="demo-note">这些请求和响应仅用于演示交互，没有发送至真实服务。</p>`)}
function settingsDialog(){state.modal='settings';showDialog('连接设置',`<div class="setting-field"><label class="form-label">服务地址 <small>baseUrl</small></label><input class="big-input" id="setting-base" value="${esc(state.settings.baseUrl)}" placeholder="https://服务地址/上下文"></div><div class="setting-field"><label class="form-label">OBS 桶覆盖 <small>可选</small></label><input class="big-input" id="setting-bucket" value="${esc(state.settings.bucket)}" placeholder="默认 receipt + regionCode"></div><div class="key-status">${icon('lock')}<div><b>本地安全存储</b><small>正式应用使用系统钥匙串保护密钥</small></div></div><p class="demo-note">当前为高保真 HTML 原型，只保存演示服务地址，不导入或保存真实密钥。</p>`,`<button class="btn quiet" data-action="close">取消</button><button class="btn primary" data-action="save-settings">保存设置</button>`)}
// 数据查询弹层：对齐 App 的四张物理表直查（WO_INFO / WO_BIZ_INFO / WO_SIGN_INFO / WO_PIC_INFO）。
const tableNames=[['WO_INFO','工单表'],['WO_BIZ_INFO','报文表'],['WO_SIGN_INFO','签字表'],['WO_PIC_INFO','图片表']];
function tableDialog(){state.modal='table';showDialog('数据查询',`<div class="table-tabs">${tableNames.map(([k,l])=>`<button class="${state.table===k?'active':''}" data-action="table-kind" data-id="${k}">${l}<span class="mono">${k}</span></button>`).join('')}</div><div class="table-form"><label>单据号<input id="table-case" placeholder="输入完整单据号，可单独查询" value="${esc(work().caseNo)}"></label><label>受理流水<input id="table-sys" placeholder="按受理流水查询需选择业务月份"></label><label>业务月份<input type="month" id="table-month" value="${esc(state.query.start)}"></label>${state.table==='WO_PIC_INFO'?`<label>图片序号<input id="table-picseq" placeholder="如 1,2,3"></label>`:''}<button class="btn primary" data-action="table-run">${icon('search')}查询</button></div><div id="table-result">${state.tableResult||`<p class="field-help" style="margin:4px 0 0">至少填写一个条件；单据号可单独查询，受理流水需搭配业务月份。结果仅展示前 8 列。</p>`}</div>`,'','table-dialog')}
// 按表生成演示结果：工单表展示当前工单前 8 列，其余表展示关联文件清单。
function runTableQuery(){const w=work();let head=[],rows=[];
 if(state.table==='WO_INFO'){head=Object.keys(w).slice(0,8);rows=[head.map(k=>w[k]??'—')]}
 else if(state.table==='WO_BIZ_INFO'){head=['报文类型','文件名','解析状态','大小'];rows=[['原始报文',`${w.caseNo}_${w.opCode}.txt`,'JSON · 已解析','4.2 KB'],['受理内容',`${w.caseNo}_${w.opCode}_oprInfo.txt`,'XML · 已解析','2.8 KB'],['H5 报文',`${w.caseNo}_${w.opCode}_h5.txt`,'JSON · 已解析','1.6 KB']]}
 else if(state.table==='WO_SIGN_INFO'){head=['文件类型','文件名','签署状态','大小'];rows=[['客户签字',`signature_01.svg`,'已完成','18 KB'],['受理人员签字',`signature_02.svg`,'已完成','17 KB']]}
 else{head=['图片序号','文件类型','文件名','大小'];rows=[['1','证件正面',`attachment_01.svg`,'96 KB'],['2','证件反面',`attachment_02.svg`,'98 KB'],['3','业务附件',`attachment_03.svg`,'87 KB']]}
 state.tableResult=`<div class="table-wrap"><table class="data-table"><thead><tr>${head.map(h=>`<th>${h}</th>`).join('')}</tr></thead><tbody>${rows.map(r=>`<tr>${r.map(c=>`<td class="mono">${esc(c)}</td>`).join('')}</tr>`).join('')}</tbody></table></div><p class="field-help" style="margin-bottom:0">${state.table} · 命中 ${rows.length} 行 · 仅展示前 8 列（演示数据）</p>`;tableDialog()}
function copy(text){if(navigator.clipboard?.writeText)navigator.clipboard.writeText(String(text)).then(()=>toast('已复制')).catch(()=>fallbackCopy(text));else fallbackCopy(text)}
function fallbackCopy(text){const input=document.createElement('textarea');input.value=String(text);input.style.cssText='position:fixed;left:-9999px';document.body.append(input);input.select();const ok=document.execCommand('copy');input.remove();toast(ok?'已复制':'浏览器未授权剪贴板，可选中文字复制')}
function download(name,text,type='application/json'){const blob=new Blob([text],{type}),url=URL.createObjectURL(blob),a=document.createElement('a');a.href=url;a.download=name;a.click();setTimeout(()=>URL.revokeObjectURL(url),2000);toast('已开始下载 '+name)}
// 下载 PDF 是合法的三页演示文件；自定义阅读区展示同一业务场景的高保真版式。
function samplePdf(){const objects=[],add=v=>{objects.push(v);return objects.length};add('<< /Type /Catalog /Pages 2 0 R >>');add('<< /Type /Pages /Kids [4 0 R 6 0 R 8 0 R] /Count 3 >>');add('<< /Type /Font /Subtype /Type1 /BaseFont /Helvetica >>');for(let n=1;n<=3;n++){add(`<< /Type /Page /Parent 2 0 R /MediaBox [0 0 595 842] /Resources << /Font << /F1 3 0 R >> >> /Contents ${objects.length+2} 0 R >>`);const txt=`BT /F1 22 Tf 58 745 Td (NPL - DEMO RECEIPT) Tj 0 -48 Td /F1 11 Tf (Case: ${work().caseNo}) Tj 0 -25 Td (Page ${n} of 3 - Local UI prototype only.) Tj 0 -25 Td (No business or legal effect.) Tj ET`;add(`<< /Length ${txt.length} >>\nstream\n${txt}\nendstream`)}let pdf='%PDF-1.4\n',offsets=[0];objects.forEach((o,i)=>{offsets.push(pdf.length);pdf+=`${i+1} 0 obj\n${o}\nendobj\n`});const xref=pdf.length;pdf+=`xref\n0 ${objects.length+1}\n0000000000 65535 f \n`+offsets.slice(1).map(o=>String(o).padStart(10,'0')+' 00000 n \n').join('')+`trailer\n<< /Size ${objects.length+1} /Root 1 0 R >>\nstartxref\n${xref}\n%%EOF`;return pdf}
function relatedLog(view){const maps={message:'/api/wobiz/queryList',sign:'/api/wosign/queryList',picture:'/api/wopic/queryList'};if(!maps[view]&&view!=='pdf')return;const key=work().caseNo+view;if(state.cache.has(key)){state.cacheHits++;return}const body=view==='pdf'?{bucketName:state.settings.bucket||'receipt025',objectName:work().caseNo+'.pdf',ext8:work().ext8}:{caseNo:work().caseNo,opMonth:work().opMonth};state.logs.unshift({path:maps[view]||'/test/un_look',body,status:200,response:view==='pdf'?'二进制演示文件 · 3 页':[{caseNo:work().caseNo,opMonth:work().opMonth,type:view}]});state.cache.set(key,true)}
function navigate(view){if(state.selected===null){toast('请先选择一份工单，再查看关联资料');return}state.view=view;state.pdfFull=false;state.pdfPage=1;relatedLog(view);render()}
// 事件统一委托，避免重绘后按钮失效；所有可见动作均有对应行为。
document.addEventListener('click',e=>{const b=e.target.closest('[data-action]');if(!b)return;const a=b.dataset.action,id=b.dataset.id;
 const actions={
 search:openSearch,close:closeDialog,settings:settingsDialog,logs:logsDialog,
 'data-query':()=>{state.tableResult=null;tableDialog()},'table-kind':()=>{state.table=id;state.tableResult=null;tableDialog()},'table-run':runTableQuery,
 choose:()=>{state.selected=+id;state.view='details';state.fieldQuery='';state.frames=[];state.pdfPage=1;state.zoom=100;render()},results:()=>{state.selected=null;state.view='details';render()},nav:()=>navigate(id),
 'copy-work':()=>copy(work().caseNo),'copy-field':()=>copy(work()[id]??''),'export-work':()=>download(work().caseNo+'.json',JSON.stringify(work(),null,2)),
 'field-mode':()=>{state.grouped=id==='group';render()},
 'pdf-full':()=>{state.view='pdf';state.pdfFull=!state.pdfFull;render()},thumbnails:()=>{state.thumbs=!state.thumbs;const p=state.pdfPage;render();document.querySelector(`#pdf-page-${p}`)?.scrollIntoView({block:'start'})},'pdf-page':()=>document.querySelector(`#pdf-page-${id}`)?.scrollIntoView({behavior:'smooth',block:'start'}),
 'zoom-in':()=>{state.fit='manual';state.zoom=Math.min(190,state.zoom+10);applyZoom()},'zoom-out':()=>{state.fit='manual';state.zoom=Math.max(40,state.zoom-10);applyZoom()},'download-pdf':()=>download(work().caseNo+'.pdf',samplePdf(),'application/pdf'),
 'query-kind':()=>{state.query.kind=id;state.query.value=id==='phoneNo'?'13800000000':id==='caseNo'?demoWork().caseNo:demoWork().sysAccept;openSearch()},'query-range':()=>{state.query.range=id==='range';if(state.query.range&&state.query.end<state.query.start)state.query.end=state.query.start;openSearch()},'query-shortcut':()=>{const count=+id;state.query.start=`2026-${String(10-count).padStart(2,'0')}`;state.query.end='2026-09';state.query.range=count>1;openSearch()},
 'run-search':()=>runSearch(),'cancel-query':()=>{const r=state.running;r.cancelled=true;clearTimeout(r.timer);finishSearch(r.rows||[],true)},'retry-query':()=>{state.scenario='normal';runSearch(true)},scenario:()=>{state.scenario=id;openSearch()},
 history:()=>{const history=state.history.length||state.historyCleared?state.history:[{kind:'phoneNo',value:'13800000000',start:'2026-09',end:'2026-09',range:false},{kind:'sysAccept',value:demoWork().sysAccept,start:'2026-09',end:'2026-09',range:false}];state.query={...history[+id]};openSearch()},'clear-history':()=>{state.history=[];state.historyCleared=true;overlay.querySelector('.search-recent').innerHTML='<h4>最近查询</h4><p class="field-help">查询历史已清空</p>'},requery:()=>{openSearch();runSearch(true)},
 'cache-clear':()=>{state.cache.clear();state.cacheHits=0;toast('演示缓存已清空');if(state.modal==='logs')logsDialog()},
 'save-settings':()=>{const value=document.querySelector('#setting-base').value.trim();try{const u=new URL(value);if(!['https:','http:'].includes(u.protocol)||u.username||u.password||u.search||u.hash)throw Error()}catch{return toast('请输入合法的 HTTP / HTTPS 服务地址，不包含账号密码或查询参数')}state.settings={baseUrl:value.replace(/\/$/,''),bucket:document.querySelector('#setting-bucket').value.trim()};try{localStorage.setItem('npl-prototype-settings',JSON.stringify(state.settings))}catch{}state.cache.clear();closeDialog();toast('演示设置已保存到本机')},
 more:()=>{state.modal='more';showDialog('更多操作',`<button class="recent-item" data-action="search">${icon('search')}查询工单 ${icon('chevron')}</button><button class="recent-item" data-action="data-query">${icon('grid')}数据查询 ${icon('chevron')}</button><button class="recent-item" data-action="settings">${icon('settings')}连接设置 ${icon('chevron')}</button><button class="recent-item" data-action="logs">${icon('code')}接口记录 <small>${state.logs.length} 次</small></button><button class="recent-item" data-action="cache-clear">${icon('refresh')}清空查询缓存 <small>命中 ${state.cacheHits} 次</small></button>`)},
 'image-full':()=>{state.modal='image';showDialog(state.view==='sign'?'签字影像':'业务附件',`<div class="image-full">${state.view==='sign'?signSvg:`<div style="padding:30px;background:white;border:1px solid #dce5f0;border-radius:9px"><h3>演示附件 ${+id+1}</h3><p class="muted">此图用于验证图片浏览交互</p></div>`}</div>`,`<button class="btn primary" data-action="download-image" data-id="${id}">${icon('download')}下载图片</button>`)},
 'download-image':()=>download(`${state.view==='sign'?'signature':'attachment'}_${+id+1}.svg`,state.view==='sign'?signSvg.replace('<svg ','<svg xmlns="http://www.w3.org/2000/svg" '):`<svg xmlns="http://www.w3.org/2000/svg" width="640" height="400"><rect width="640" height="400" rx="20" fill="#eef4ff"/><text x="40" y="80" font-size="24" fill="#42628c">DEMO ATTACHMENT ${+id+1}</text></svg>`,'image/svg+xml'),
 'download-gallery':()=>{const isSign=state.view==='sign';for(let n=0;n<(isSign?2:3);n++)setTimeout(()=>download(`${isSign?'signature':'attachment'}_${n+1}.svg`,isSign?signSvg.replace('<svg ','<svg xmlns="http://www.w3.org/2000/svg" '):`<svg xmlns="http://www.w3.org/2000/svg" width="640" height="400"><rect width="640" height="400" fill="#eef4ff"/><text x="40" y="80" font-size="24">DEMO ATTACHMENT ${n+1}</text></svg>`,'image/svg+xml'),n*200)},
 'copy-message':()=>copy(currentMessage().source),'download-message':()=>download(`${work().caseNo}_message_${state.messageIndex+1}.txt`,currentMessage().source,'text/plain;charset=utf-8'),
 'message-raw':()=>{state.messageRaw=!state.messageRaw;refreshMessage()},'message-fold':()=>{state.messageCollapsed.has('$')?state.messageCollapsed.clear():state.messageCollapsed.add('$');document.querySelector('#message-tree').innerHTML=messageTree()},'tree-toggle':()=>{state.messageCollapsed.has(id)?state.messageCollapsed.delete(id):state.messageCollapsed.add(id);document.querySelector('#message-tree').innerHTML=messageTree()},
 'message-focus':()=>{const n=visibleNodes[+id];state.frames.push({label:n.name,value:n.value});state.messageKey='';state.messageKeyword='';state.messageMode='auto';state.messageCollapsed.clear();state.messageRaw=false;refreshMessage()},'message-back':()=>{state.frames=state.frames.slice(0,+id+1);state.messageKey='';state.messageKeyword='';state.messageMode='auto';state.messageCollapsed.clear();refreshMessage()},
 'message-full':()=>{const view=document.querySelector('.message-view');view.classList.toggle('reading-fullscreen');b.innerHTML=icon(view.classList.contains('reading-fullscreen')?'collapse':'expand');b.title=view.classList.contains('reading-fullscreen')?'退出全屏':'全屏报文'},
 };
 actions[a]?.();
});
document.addEventListener('input',e=>{const t=e.target,v=t.value;switch(t.id){case'query-value':state.query.value=v;break;case'query-start':state.query.start=v;break;case'query-end':state.query.end=v;break;case'order-filter':state.orderQuery=v;document.querySelector('.orders').innerHTML=state.works.map((w,i)=>JSON.stringify(w).toLowerCase().includes(v.toLowerCase())?orderCard(w,i):'').join('')||'<p class="field-help">没有匹配结果</p>';break;case'field-search':state.fieldQuery=v;document.querySelector('#fields-content').innerHTML=fieldsMarkup();break;case'message-key':state.messageKey=v;document.querySelector('#message-tree').innerHTML=messageTree();break;case'message-keyword':state.messageKeyword=v;document.querySelector('#message-tree').innerHTML=messageTree();break}});
document.addEventListener('change',e=>{const t=e.target;if(t.id==='message-file'){state.messageIndex=+t.value;state.frames=[];state.messageMode='auto';state.messageRaw=false;state.messageKey=state.messageKeyword='';state.messageCollapsed.clear();refreshMessage()}if(t.id==='message-format'){state.messageMode=t.value;refreshMessage()}if(t.id==='pdf-fit'){state.fit=t.value;if(t.value!=='page')state.zoom=100;applyZoom()}});
document.addEventListener('keydown',e=>{if((e.metaKey||e.ctrlKey)&&e.key.toLowerCase()==='k'){e.preventDefault();if(!state.running)openSearch()}if(e.key==='Escape'){if(state.running)return;if(state.modal){closeDialog();return}if(state.pdfFull){state.pdfFull=false;render()}else document.querySelector('.reading-fullscreen')?.classList.remove('reading-fullscreen')}if(e.key==='Enter'&&e.target.id==='query-value'){e.preventDefault();runSearch()}if(e.key==='Tab'&&overlay.children.length){const nodes=[...overlay.querySelectorAll('button,input,select,[tabindex="0"]')].filter(el=>!el.disabled&&el.offsetParent);if(!nodes.length)return;if(e.shiftKey&&document.activeElement===nodes[0]){e.preventDefault();nodes.at(-1).focus()}else if(!e.shiftKey&&document.activeElement===nodes.at(-1)){e.preventDefault();nodes[0].focus()}}});
window.addEventListener('message',e=>{if(e.source!==parent||e.data?.type!=='prototype-scene')return;if(state.running){state.running.cancelled=true;clearTimeout(state.running.timer);state.running=null}overlay.innerHTML='';state.modal=null;if(e.data.scene==='search'){openSearch();return}if(!state.works.length)state.works=[demoWork(0),demoWork(1),demoWork(2)];state.selected=0;state.frames=[];navigate(e.data.scene)});
try{const saved=JSON.parse(localStorage.getItem('npl-prototype-settings'));if(saved?.baseUrl)state.settings=saved}catch{}
render();
